V13_OCEANIA_CHUNK01_SOURCE_CANDIDATES = [
    {
        "source_id": "ofc_official",
        "name": "Oceania Football Confederation",
        "base_url": "https://www.oceaniafootball.com/",
        "region": "OCEANIA",
        "layer": "REGIONAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "OCEANIA",
        "status": "CANDIDATE",
        "notes": "Continental Oceania football source covering OFC competitions, member associations, fixtures, results and match information.",
    },
    {
        "source_id": "american_samoa_ffas_official",
        "name": "Football Federation American Samoa",
        "base_url": "https://www.ffas.as/",
        "region": "OCEANIA",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "AMERICAN_SAMOA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "cook_islands_cifa_official",
        "name": "Cook Islands Football Association",
        "base_url": "https://www.cookislandsfootball.com/",
        "region": "OCEANIA",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "COOK_ISLANDS",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "fiji_football_official",
        "name": "Fiji Football Association",
        "base_url": "https://www.fijifootball.com.fj/",
        "region": "OCEANIA",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "FIJI",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "new_caledonia_federation_official",
        "name": "New Caledonia Football Federation",
        "base_url": "https://www.fedcalfoot.com/",
        "region": "OCEANIA",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "NEW_CALEDONIA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "new_zealand_football_official",
        "name": "New Zealand Football",
        "base_url": "https://www.nzfootball.co.nz/",
        "region": "OCEANIA",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "NEW_ZEALAND",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "papua_new_guinea_football_official",
        "name": "Papua New Guinea Football Association",
        "base_url": "https://www.pngfootball.com/",
        "region": "OCEANIA",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "PAPUA_NEW_GUINEA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "samoa_football_federation_official",
        "name": "Football Federation Samoa",
        "base_url": "https://www.samoafootball.com/",
        "region": "OCEANIA",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "SAMOA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "solomon_islands_football_official",
        "name": "Solomon Islands Football Federation",
        "base_url": "https://www.siff.com.sb/",
        "region": "OCEANIA",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "SOLOMON_ISLANDS",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "tahiti_football_federation_official",
        "name": "Tahiti Football Federation",
        "base_url": "https://www.ftf.pf/",
        "region": "OCEANIA",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "TAHITI",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "tonga_football_association_official",
        "name": "Tonga Football Association",
        "base_url": "https://www.tongafootball.to/",
        "region": "OCEANIA",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "TONGA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "vanuatu_football_official",
        "name": "Vanuatu Football Federation",
        "base_url": "https://www.vff.vu/",
        "region": "OCEANIA",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "VANUATU",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
]
