V13_ASIA_WEST_SOURCE_CANDIDATES = [
    {
        "source_id": "waff_official",
        "name": "West Asian Football Federation",
        "base_url": "https://the-waff.com/",
        "region": "ASIA_WEST",
        "layer": "REGIONAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "WEST_ASIA",
        "status": "CANDIDATE",
        "notes": "Regional West Asian football source covering WAFF competitions, member associations, fixtures, results and football information.",
    },
    {
        "source_id": "afc_west",
        "name": "Asian Football Confederation West Zone",
        "base_url": "https://www.the-afc.com/",
        "region": "ASIA_WEST",
        "layer": "REGIONAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "WEST_ASIA",
        "status": "CANDIDATE",
        "notes": "AFC regional source for West Asian competitions, fixtures, results and match information.",
    },
    {
        "source_id": "bahrain_bfa_official",
        "name": "Bahrain Football Association",
        "base_url": "https://bahrainfa.com/",
        "region": "ASIA_WEST",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "BAHRAIN",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "iraq_ifa_official",
        "name": "Iraqi Football Association",
        "base_url": "https://ifa.iq/",
        "region": "ASIA_WEST",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "IRAQ",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "jordan_jfa_official",
        "name": "Jordan Football Association",
        "base_url": "https://www.jfa.jo/",
        "region": "ASIA_WEST",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "JORDAN",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "kuwait_kfa_official",
        "name": "Kuwait Football Association",
        "base_url": "https://www.kfa.org.kw/",
        "region": "ASIA_WEST",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "KUWAIT",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "lebanon_lfa_official",
        "name": "Lebanese Football Association",
        "base_url": "https://www.lebanesefootballassociation.com/",
        "region": "ASIA_WEST",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "LEBANON",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "oman_ofa_official",
        "name": "Oman Football Association",
        "base_url": "https://ofa.om/",
        "region": "ASIA_WEST",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "OMAN",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "palestine_pfa_official",
        "name": "Palestine Football Association",
        "base_url": "https://www.pfa.ps/",
        "region": "ASIA_WEST",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "PALESTINE",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "qatar_qfa_official",
        "name": "Qatar Football Association",
        "base_url": "https://www.qfa.qa/",
        "region": "ASIA_WEST",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "QATAR",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "saudi_saff_official",
        "name": "Saudi Arabian Football Federation",
        "base_url": "https://www.saff.com.sa/",
        "region": "ASIA_WEST",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "SAUDI_ARABIA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "syria_sfa_official",
        "name": "Syrian Football Association",
        "base_url": "https://syrfa.com/",
        "region": "ASIA_WEST",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "SYRIA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "uae_fa_official",
        "name": "United Arab Emirates Football Association",
        "base_url": "https://www.uaefa.ae/",
        "region": "ASIA_WEST",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "UNITED_ARAB_EMIRATES",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "yemen_yfa_official",
        "name": "Yemen Football Association",
        "base_url": "https://www.yemenfa.com/",
        "region": "ASIA_WEST",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "YEMEN",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
]
