V13_EUROPE_CHUNK02_SOURCE_CANDIDATES = [
    {
        "source_id": "cyprus_cfa_official",
        "name": "Cyprus Football Association",
        "base_url": "https://www.cfa.com.cy/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "CYPRUS",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "czechia_facr_official",
        "name": "Football Association of the Czech Republic",
        "base_url": "https://www.fotbal.cz/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "CZECHIA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "denmark_dbU_official",
        "name": "Danish Football Association",
        "base_url": "https://www.dbu.dk/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "DENMARK",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "england_fa_official",
        "name": "The Football Association",
        "base_url": "https://www.thefa.com/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "ENGLAND",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "estonia_efa_official",
        "name": "Estonian Football Association",
        "base_url": "https://jalgpall.ee/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "ESTONIA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "faroe_islands_ffi_official",
        "name": "Football Association of the Faroe Islands",
        "base_url": "https://www.fsf.fo/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "FAROE_ISLANDS",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "finland_spl_official",
        "name": "Football Association of Finland",
        "base_url": "https://www.palloliitto.fi/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "FINLAND",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "france_fff_official",
        "name": "French Football Federation",
        "base_url": "https://www.fff.fr/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "FRANCE",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "georgia_gff_official",
        "name": "Georgian Football Federation",
        "base_url": "https://gff.ge/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "GEORGIA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "germany_dfb_official",
        "name": "German Football Association",
        "base_url": "https://www.dfb.de/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "GERMANY",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "gibraltar_gfa_official",
        "name": "Gibraltar Football Association",
        "base_url": "https://www.gibraltarfa.com/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "GIBRALTAR",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
]
