V13_OCEANIA_SOURCE_CANDIDATES = [
    {
        "source_id": "ofc_official",
        "name": "Oceania Football Confederation",
        "base_url": "https://www.oceaniafootball.com/",
        "layer": "OFFICIAL",
        "data_classes": ["competition", "fixture", "schedule", "results", "team", "player", "lineup", "venue"],
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "OCEANIA_REGIONAL",
        "status": "CANDIDATE",
    },
    {
        "source_id": "ofc_pro_league",
        "name": "OFC Professional League",
        "base_url": "https://www.ofcproleague.com/",
        "layer": "OFFICIAL",
        "data_classes": ["competition", "fixture", "schedule", "results", "team", "lineup", "venue"],
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "OCEANIA_PROFESSIONAL",
        "status": "CANDIDATE",
    },
    {
        "source_id": "openfootball_data",
        "name": "Open Football Data",
        "base_url": "https://openfootball.github.io/",
        "layer": "PUBLIC_DATA",
        "data_classes": ["competition", "fixture", "schedule", "results", "standings"],
        "access_type": "PUBLIC_DATA",
        "free": True,
        "coverage_scope": "GLOBAL_WHERE_AVAILABLE",
        "status": "CANDIDATE",
    },
    {
        "source_id": "api_football_free_tier",
        "name": "API-Football Free Tier",
        "base_url": "https://www.api-football.com/",
        "layer": "PUBLIC_API",
        "data_classes": ["fixture", "schedule", "results", "standings", "team", "player", "lineup", "statistics"],
        "access_type": "FREE_TIER",
        "free": True,
        "coverage_scope": "GLOBAL_WHERE_AVAILABLE",
        "status": "CANDIDATE",
    },

    {"source_id": "new_zealand_football_official", "name": "New Zealand Football", "base_url": "https://www.nzfootball.co.nz/", "layer": "OFFICIAL", "data_classes": ["competition", "fixture", "schedule", "results", "team"], "access_type": "PUBLIC_WEB", "free": True, "coverage_scope": "NEW_ZEALAND", "status": "CANDIDATE"},
    {"source_id": "fiji_football_official", "name": "Fiji Football Association", "base_url": "https://www.fijifootball.com/", "layer": "OFFICIAL", "data_classes": ["competition", "fixture", "schedule", "results", "team"], "access_type": "PUBLIC_WEB", "free": True, "coverage_scope": "FIJI", "status": "CANDIDATE"},
    {"source_id": "papua_new_guinea_football_official", "name": "Papua New Guinea Football Association", "base_url": "https://www.pngfootball.com/", "layer": "OFFICIAL", "data_classes": ["competition", "fixture", "schedule", "results", "team"], "access_type": "PUBLIC_WEB", "free": True, "coverage_scope": "PAPUA_NEW_GUINEA", "status": "CANDIDATE"},
    {"source_id": "solomon_islands_football_official", "name": "Solomon Islands Football Federation", "base_url": "https://www.siff.com.sb/", "layer": "OFFICIAL", "data_classes": ["competition", "fixture", "schedule", "results", "team"], "access_type": "PUBLIC_WEB", "free": True, "coverage_scope": "SOLOMON_ISLANDS", "status": "CANDIDATE"},
    {"source_id": "vanuatu_football_official", "name": "Vanuatu Football Federation", "base_url": "https://www.vff.vu/", "layer": "OFFICIAL", "data_classes": ["competition", "fixture", "schedule", "results", "team"], "access_type": "PUBLIC_WEB", "free": True, "coverage_scope": "VANUATU", "status": "CANDIDATE"},
    {"source_id": "tahiti_football_official", "name": "Tahiti Football Federation", "base_url": "https://www.ftf.pf/", "layer": "OFFICIAL", "data_classes": ["competition", "fixture", "schedule", "results", "team"], "access_type": "PUBLIC_WEB", "free": True, "coverage_scope": "TAHITI", "status": "CANDIDATE"},
    {"source_id": "new_caledonia_football_official", "name": "New Caledonia Football Federation", "base_url": "https://www.fedcalfoot.com/", "layer": "OFFICIAL", "data_classes": ["competition", "fixture", "schedule", "results", "team"], "access_type": "PUBLIC_WEB", "free": True, "coverage_scope": "NEW_CALEDONIA", "status": "CANDIDATE"},
    {"source_id": "samoa_football_official", "name": "Football Federation Samoa", "base_url": "https://www.ffsamoa.ws/", "layer": "OFFICIAL", "data_classes": ["competition", "fixture", "schedule", "results", "team"], "access_type": "PUBLIC_WEB", "free": True, "coverage_scope": "SAMOA", "status": "CANDIDATE"},
    {"source_id": "american_samoa_football_official", "name": "American Samoa Football Association", "base_url": "https://www.asfa.as/", "layer": "OFFICIAL", "data_classes": ["competition", "fixture", "schedule", "results", "team"], "access_type": "PUBLIC_WEB", "free": True, "coverage_scope": "AMERICAN_SAMOA", "status": "CANDIDATE"},
    {"source_id": "tonga_football_official", "name": "Tonga Football Association", "base_url": "https://www.tongafootball.com/", "layer": "OFFICIAL", "data_classes": ["competition", "fixture", "schedule", "results", "team"], "access_type": "PUBLIC_WEB", "free": True, "coverage_scope": "TONGA", "status": "CANDIDATE"},
    {"source_id": "cook_islands_football_official", "name": "Cook Islands Football Association", "base_url": "https://www.cookislandsfootball.com/", "layer": "OFFICIAL", "data_classes": ["competition", "fixture", "schedule", "results", "team"], "access_type": "PUBLIC_WEB", "free": True, "coverage_scope": "COOK_ISLANDS", "status": "CANDIDATE"},
]
