V13_ASIA_EAST_SOURCE_CANDIDATES = [
    {
        "source_id": "eaff_official",
        "name": "East Asian Football Federation",
        "base_url": "https://eaff.com/",
        "region": "ASIA_EAST",
        "layer": "REGIONAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "EAST_ASIA",
        "status": "CANDIDATE",
        "notes": "Regional East Asian football source covering EAFF competitions, member associations, fixtures, results and football information.",
    },
    {
        "source_id": "afc_east",
        "name": "Asian Football Confederation East Zone",
        "base_url": "https://www.the-afc.com/",
        "region": "ASIA_EAST",
        "layer": "REGIONAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "EAST_ASIA",
        "status": "CANDIDATE",
        "notes": "AFC regional source for East Asian competitions, fixtures, results and match information.",
    },
    {
        "source_id": "china_cfa_official",
        "name": "Chinese Football Association",
        "base_url": "https://www.thecfa.cn/",
        "region": "ASIA_EAST",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "CHINA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "chinese_taipei_ctfa_official",
        "name": "Chinese Taipei Football Association",
        "base_url": "https://www.ctfa.com.tw/",
        "region": "ASIA_EAST",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "CHINESE_TAIPEI",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "dpr_korea_ff_official",
        "name": "DPR Korea Football Association",
        "base_url": "https://www.kfa.org.kp/",
        "region": "ASIA_EAST",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "DPR_KOREA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "guam_gfa_official",
        "name": "Guam Football Association",
        "base_url": "https://www.guamfa.net/",
        "region": "ASIA_EAST",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "GUAM",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "hong_kong_hkfa_official",
        "name": "Hong Kong Football Association",
        "base_url": "https://www.hkfa.com/",
        "region": "ASIA_EAST",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "HONG_KONG",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "japan_jfa_official",
        "name": "Japan Football Association",
        "base_url": "https://www.jfa.jp/",
        "region": "ASIA_EAST",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "JAPAN",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "korea_kfa_official",
        "name": "Korea Football Association",
        "base_url": "https://www.kfa.or.kr/",
        "region": "ASIA_EAST",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "KOREA_REPUBLIC",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "macau_fmac_official",
        "name": "Football Association of Macau, China",
        "base_url": "https://www.macaufa.org.mo/",
        "region": "ASIA_EAST",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "MACAU",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "mongolia_mff_official",
        "name": "Mongolian Football Federation",
        "base_url": "https://the-mff.mn/",
        "region": "ASIA_EAST",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "MONGOLIA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "northern_mariana_islands_nmifa_official",
        "name": "Northern Mariana Islands Football Association",
        "base_url": "https://nmifa.com/",
        "region": "ASIA_EAST",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "NORTHERN_MARIANA_ISLANDS",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
]
