V13_EUROPE_CHUNK05_SOURCE_CANDIDATES = [
    {
        "source_id": "russia_rfu_official",
        "name": "Russian Football Union",
        "base_url": "https://rfs.ru/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "RUSSIA",
        "status": "CANDIDATE",
        "notes": "UEFA-listed national association; candidate source only at this stage.",
    },
    {
        "source_id": "san_marino_fsgc_official",
        "name": "San Marino Football Federation",
        "base_url": "https://www.fsgc.sm/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "SAN_MARINO",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "scotland_sfa_official",
        "name": "Scottish Football Association",
        "base_url": "https://www.scottishfa.co.uk/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "SCOTLAND",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "serbia_fss_official",
        "name": "Football Association of Serbia",
        "base_url": "https://fss.rs/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "SERBIA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "slovakia_sfz_official",
        "name": "Slovak Football Association",
        "base_url": "https://futbalsfz.sk/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "SLOVAKIA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "slovenia_nzs_official",
        "name": "Football Association of Slovenia",
        "base_url": "https://www.nzs.si/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "SLOVENIA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "spain_rfef_official",
        "name": "Royal Spanish Football Federation",
        "base_url": "https://rfef.es/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "SPAIN",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "sweden_svff_official",
        "name": "Swedish Football Association",
        "base_url": "https://www.svenskfotboll.se/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "SWEDEN",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "switzerland_sfv_official",
        "name": "Swiss Football Association",
        "base_url": "https://www.football.ch/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "SWITZERLAND",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "turkiye_tff_official",
        "name": "Turkish Football Federation",
        "base_url": "https://www.tff.org/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "TURKIYE",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "ukraine_uaf_official",
        "name": "Ukrainian Association of Football",
        "base_url": "https://uaf.ua/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "UKRAINE",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "wales_faw_official",
        "name": "Football Association of Wales",
        "base_url": "https://faw.cymru/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "WALES",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
]
