V13_EUROPE_CHUNK04_SOURCE_CANDIDATES = [
    {
        "source_id": "malta_mfa_official",
        "name": "Malta Football Association",
        "base_url": "https://www.mfa.com.mt/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "MALTA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "moldova_fmf_official",
        "name": "Moldovan Football Federation",
        "base_url": "https://fmf.md/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "MOLDOVA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "montenegro_fscg_official",
        "name": "Football Association of Montenegro",
        "base_url": "https://fscg.me/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "MONTENEGRO",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "netherlands_knvb_official",
        "name": "Royal Netherlands Football Association",
        "base_url": "https://www.knvb.nl/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "NETHERLANDS",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "north_macedonia_ffm_official",
        "name": "Football Federation of North Macedonia",
        "base_url": "https://ffm.mk/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "NORTH_MACEDONIA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "northern_ireland_ifa_official",
        "name": "Irish Football Association",
        "base_url": "https://www.irishfa.com/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "NORTHERN_IRELAND",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "norway_nff_official",
        "name": "Norwegian Football Federation",
        "base_url": "https://www.fotball.no/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "NORWAY",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "poland_pzpn_official",
        "name": "Polish Football Association",
        "base_url": "https://pzpn.pl/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "POLAND",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "portugal_fpf_official",
        "name": "Portuguese Football Federation",
        "base_url": "https://www.fpf.pt/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "PORTUGAL",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "republic_of_ireland_fai_official",
        "name": "Football Association of Ireland",
        "base_url": "https://www.fai.ie/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "REPUBLIC_OF_IRELAND",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "romania_frF_official",
        "name": "Romanian Football Federation",
        "base_url": "https://www.frf.ro/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "ROMANIA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
]
