V13_AMERICAS_CONMEBOL_CHUNK01_SOURCE_CANDIDATES = [
    {
        "source_id": "conmebol_official",
        "name": "South American Football Confederation",
        "base_url": "https://www.conmebol.com/",
        "region": "AMERICAS",
        "layer": "REGIONAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "SOUTH_AMERICA",
        "status": "CANDIDATE",
        "notes": "Continental South American football source covering competitions, member associations, fixtures, results and match information.",
    },
    {
        "source_id": "argentina_afa_official",
        "name": "Argentine Football Association",
        "base_url": "https://www.afa.com.ar/",
        "region": "AMERICAS",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "ARGENTINA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "bolivia_fbf_official",
        "name": "Bolivian Football Federation",
        "base_url": "https://www.fbf.com.bo/",
        "region": "AMERICAS",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "BOLIVIA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "brazil_cbf_official",
        "name": "Brazilian Football Confederation",
        "base_url": "https://www.cbf.com.br/",
        "region": "AMERICAS",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "BRAZIL",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "chile_anfp_official",
        "name": "National Professional Football Association of Chile",
        "base_url": "https://www.anfp.cl/",
        "region": "AMERICAS",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "CHILE",
        "status": "CANDIDATE",
        "notes": "Chilean professional football source.",
    },
    {
        "source_id": "colombia_fcf_official",
        "name": "Colombian Football Federation",
        "base_url": "https://fcf.com.co/",
        "region": "AMERICAS",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "COLOMBIA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "ecuador_fef_official",
        "name": "Ecuadorian Football Federation",
        "base_url": "https://www.fef.ec/",
        "region": "AMERICAS",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "ECUADOR",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "paraguay_apf_official",
        "name": "Paraguayan Football Association",
        "base_url": "https://www.apf.org.py/",
        "region": "AMERICAS",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "PARAGUAY",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "peru_fpf_official",
        "name": "Peruvian Football Federation",
        "base_url": "https://fpf.org.pe/",
        "region": "AMERICAS",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "PERU",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "uruguay_auf_official",
        "name": "Uruguayan Football Association",
        "base_url": "https://www.auf.org.uy/",
        "region": "AMERICAS",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "URUGUAY",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "venezuela_fvf_official",
        "name": "Venezuelan Football Federation",
        "base_url": "https://www.fvf.com.ve/",
        "region": "AMERICAS",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "VENEZUELA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
]
