V13_EUROPE_CHUNK03_SOURCE_CANDIDATES = [
    {
        "source_id": "greece_hellenic_fa_official",
        "name": "Hellenic Football Federation",
        "base_url": "https://www.epo.gr/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "GREECE",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "hungary_mlsz_official",
        "name": "Hungarian Football Federation",
        "base_url": "https://www.mlsz.hu/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "HUNGARY",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "iceland_ksi_official",
        "name": "Football Association of Iceland",
        "base_url": "https://www.ksi.is/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "ICELAND",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "israel_ifa_official",
        "name": "Israel Football Association",
        "base_url": "https://www.football.org.il/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "ISRAEL",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "italy_figc_official",
        "name": "Italian Football Federation",
        "base_url": "https://www.figc.it/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "ITALY",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "kazakhstan_kff_official",
        "name": "Kazakhstan Football Federation",
        "base_url": "https://kff.kz/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "KAZAKHSTAN",
        "status": "CANDIDATE",
        "notes": "UEFA member association source.",
    },
    {
        "source_id": "kosovo_ffk_official",
        "name": "Football Federation of Kosovo",
        "base_url": "https://www.ffk-kosova.com/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "KOSOVO",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "latvia_lff_official",
        "name": "Latvian Football Federation",
        "base_url": "https://lff.lv/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "LATVIA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "liechtenstein_lfv_official",
        "name": "Liechtenstein Football Association",
        "base_url": "https://www.lfv.li/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "LIECHTENSTEIN",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "lithuania_lff_official",
        "name": "Lithuanian Football Federation",
        "base_url": "https://www.lff.lt/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "LITHUANIA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "luxembourg_flf_official",
        "name": "Luxembourg Football Federation",
        "base_url": "https://www.flf.lu/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "LUXEMBOURG",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
]
