V13_EUROPE_CHUNK01_SOURCE_CANDIDATES = [
    {
        "source_id": "uefa_official",
        "name": "Union of European Football Associations",
        "base_url": "https://www.uefa.com/",
        "region": "EUROPE",
        "layer": "REGIONAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "EUROPE",
        "status": "CANDIDATE",
        "notes": "Continental European football source covering UEFA competitions, member associations, fixtures, results and match information.",
    },
    {
        "source_id": "fifa_europe",
        "name": "FIFA Europe",
        "base_url": "https://www.fifa.com/",
        "region": "EUROPE",
        "layer": "REGIONAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "EUROPE",
        "status": "CANDIDATE",
        "notes": "Global football source with European national-team and competition information.",
    },
    {
        "source_id": "albania_fshf_official",
        "name": "Albanian Football Federation",
        "base_url": "https://fshf.org/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "ALBANIA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "andorra_faf_official",
        "name": "Andorran Football Federation",
        "base_url": "https://www.faf.ad/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "ANDORRA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "armenia_ffa_official",
        "name": "Football Federation of Armenia",
        "base_url": "https://www.ffa.am/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "ARMENIA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "austria_oefb_official",
        "name": "Austrian Football Association",
        "base_url": "https://www.oefb.at/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "AUSTRIA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "azerbaijan_afa_official",
        "name": "Association of Football Federations of Azerbaijan",
        "base_url": "https://www.affa.az/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "AZERBAIJAN",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "belarus_bff_official",
        "name": "Football Federation of Belarus",
        "base_url": "https://abff.by/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "BELARUS",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "belgium_rbfa_official",
        "name": "Royal Belgian Football Association",
        "base_url": "https://www.rbfa.be/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "BELGIUM",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "bosnia_and_herzegovina_nfsbih_official",
        "name": "Football Association of Bosnia and Herzegovina",
        "base_url": "https://www.nfsbih.ba/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "BOSNIA_AND_HERZEGOVINA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "bulgaria_bfu_official",
        "name": "Bulgarian Football Union",
        "base_url": "https://bfunion.bg/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "BULGARIA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "croatia_hns_official",
        "name": "Croatian Football Federation",
        "base_url": "https://hns-cff.hr/",
        "region": "EUROPE",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "CROATIA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
]
