V13_AFRICA_WAFU_B_SOURCE_CANDIDATES = [
    {
        "source_id": "wafu_b_official",
        "name": "WAFU Zone B",
        "base_url": "https://www.cafzoneouestb.com/",
        "layer": "REGIONAL_OFFICIAL",
        "data_classes": ["competition", "fixture", "schedule", "results", "match_status", "team", "player", "lineup", "venue"],
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "WAFU_B",
        "status": "CANDIDATE",
    },
    {
        "source_id": "caf_wafu_b",
        "name": "CAF WAFU-B",
        "base_url": "https://www.cafonline.com/",
        "layer": "REGIONAL_OFFICIAL",
        "data_classes": ["competition", "fixture", "schedule", "results", "match_status", "team", "player", "lineup"],
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "WAFU_B",
        "status": "CANDIDATE",
    },
    {
        "source_id": "benin_fbf_official",
        "name": "Benin Football Federation",
        "base_url": "https://febefoot.org/",
        "layer": "OFFICIAL",
        "data_classes": ["competition", "fixture", "schedule", "results", "match_status", "team", "player", "lineup"],
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "BENIN",
        "status": "CANDIDATE",
    },
    {
        "source_id": "ghana_fa_official",
        "name": "Ghana Football Association",
        "base_url": "https://www.ghanafa.org/",
        "layer": "OFFICIAL",
        "data_classes": ["competition", "fixture", "schedule", "results", "match_status", "team", "player", "lineup", "venue"],
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "GHANA",
        "status": "CANDIDATE",
    },
    {
        "source_id": "nigeria_nff_official",
        "name": "Nigeria Football Federation",
        "base_url": "https://thenff.com/",
        "layer": "OFFICIAL",
        "data_classes": ["competition", "fixture", "schedule", "results", "match_status", "team", "player", "lineup", "venue"],
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "NIGERIA",
        "status": "CANDIDATE",
    },
    {
        "source_id": "burkina_faso_fbf_fifa_profile",
        "name": "Burkinabe Football Association — FIFA profile",
        "base_url": "https://inside.fifa.com/associations/BFA/organisation",
        "layer": "OFFICIAL_PROFILE",
        "data_classes": ["association", "competition", "team", "player", "venue"],
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "BURKINA_FASO",
        "status": "CANDIDATE",
    },
    {
        "source_id": "cote_divoire_fif_fifa_profile",
        "name": "Ivorian Football Association — FIFA profile",
        "base_url": "https://inside.fifa.com/associations/CIV/organisation",
        "layer": "OFFICIAL_PROFILE",
        "data_classes": ["association", "competition", "team", "player", "venue"],
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "COTE_DIVOIRE",
        "status": "CANDIDATE",
    },
    {
        "source_id": "niger_fenifoot_fifa_profile",
        "name": "Nigerien Football Association — FIFA profile",
        "base_url": "https://inside.fifa.com/associations/NIG/organisation",
        "layer": "OFFICIAL_PROFILE",
        "data_classes": ["association", "competition", "team", "player", "venue"],
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "NIGER",
        "status": "CANDIDATE",
    },
    {
        "source_id": "togo_ftf_fifa_profile",
        "name": "Togolese Football Federation — FIFA profile",
        "base_url": "https://inside.fifa.com/about-fifa/associations/TOG",
        "layer": "OFFICIAL_PROFILE",
        "data_classes": ["association", "competition", "team", "player", "venue"],
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "TOGO",
        "status": "CANDIDATE",
    },
]
