V13_EUROPE_UEFA_COMPETITION_FAMILY_SOURCE_CANDIDATES = [
    {
        "source_id": "uefa_champions_league",
        "name": "UEFA Champions League",
        "base_url": "https://www.uefa.com/uefachampionsleague/",
        "region": "EUROPE",
        "layer": "COMPETITION",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "EUROPE_MENS_CLUB",
        "status": "CANDIDATE",
        "notes": "European men's top-tier club competition source.",
    },
    {
        "source_id": "uefa_europa_league",
        "name": "UEFA Europa League",
        "base_url": "https://www.uefa.com/uefaeuropaleague/",
        "region": "EUROPE",
        "layer": "COMPETITION",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "EUROPE_MENS_CLUB",
        "status": "CANDIDATE",
        "notes": "European men's second-tier club competition source.",
    },
    {
        "source_id": "uefa_conference_league",
        "name": "UEFA Conference League",
        "base_url": "https://www.uefa.com/uefaconferenceleague/",
        "region": "EUROPE",
        "layer": "COMPETITION",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "EUROPE_MENS_CLUB",
        "status": "CANDIDATE",
        "notes": "European men's third-tier club competition source.",
    },
    {
        "source_id": "uefa_euro",
        "name": "UEFA European Championship",
        "base_url": "https://www.uefa.com/euro/",
        "region": "EUROPE",
        "layer": "COMPETITION",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "EUROPE_MENS_NATIONAL_TEAMS",
        "status": "CANDIDATE",
        "notes": "European men's senior national-team competition source.",
    },
    {
        "source_id": "uefa_nations_league",
        "name": "UEFA Nations League",
        "base_url": "https://www.uefa.com/uefanationsleague/",
        "region": "EUROPE",
        "layer": "COMPETITION",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "EUROPE_MENS_NATIONAL_TEAMS",
        "status": "CANDIDATE",
        "notes": "European men's senior national-team competition source.",
    },
    {
        "source_id": "uefa_womens_champions_league",
        "name": "UEFA Women's Champions League",
        "base_url": "https://www.uefa.com/womenschampionsleague/",
        "region": "EUROPE",
        "layer": "COMPETITION",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "EUROPE_WOMENS_CLUB",
        "status": "CANDIDATE",
        "notes": "European women's club competition source.",
    },
    {
        "source_id": "uefa_youth_league",
        "name": "UEFA Youth League",
        "base_url": "https://www.uefa.com/uefayouthleague/",
        "region": "EUROPE",
        "layer": "COMPETITION",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "EUROPE_YOUTH_CLUB",
        "status": "CANDIDATE",
        "notes": "European youth club competition source.",
    },
]
