V13_AMERICAS_CONCACAF_CHUNK01_SOURCE_CANDIDATES = [
    {
        "source_id": "concacaf_official",
        "name": "Confederation of North Central America and Caribbean Association Football",
        "base_url": "https://www.concacaf.com/",
        "region": "AMERICAS",
        "layer": "REGIONAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "NORTH_CENTRAL_AMERICA_CARIBBEAN",
        "status": "CANDIDATE",
        "notes": "Continental regional football source covering CONCACAF competitions, member associations, fixtures, results and match information.",
    },
    {
        "source_id": "anguilla_afa_official",
        "name": "Anguilla Football Association",
        "base_url": "https://www.anguillafa.com/",
        "region": "AMERICAS",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "ANGUILLA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "antigua_barbuda_abfa_official",
        "name": "Antigua and Barbuda Football Association",
        "base_url": "https://abfafootball.com/",
        "region": "AMERICAS",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "ANTIGUA_AND_BARBUDA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "aruba_afa_official",
        "name": "Aruba Football Federation",
        "base_url": "https://www.arubafutbol.com/",
        "region": "AMERICAS",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "ARUBA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "bahamas_bfa_official",
        "name": "Bahamas Football Association",
        "base_url": "https://bahamasfa.net/",
        "region": "AMERICAS",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "BAHAMAS",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "barbados_bfa_official",
        "name": "Barbados Football Association",
        "base_url": "https://barbadosfootball.org/",
        "region": "AMERICAS",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "BARBADOS",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "belize_ffb_official",
        "name": "Football Federation of Belize",
        "base_url": "https://www.ffb.org.bz/",
        "region": "AMERICAS",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "BELIZE",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "bermuda_bfa_official",
        "name": "Bermuda Football Association",
        "base_url": "https://www.bermudafa.com/",
        "region": "AMERICAS",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "BERMUDA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "bonaire_ffb_official",
        "name": "Bonaire Football Federation",
        "base_url": "https://www.ffbonaire.com/",
        "region": "AMERICAS",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "BONAIRE",
        "status": "CANDIDATE",
        "notes": "CONCACAF member association candidate source.",
    },
]
