V13_ASIA_ASEAN_SOURCE_CANDIDATES = [
    {
        "source_id": "aff_official",
        "name": "ASEAN Football Federation",
        "base_url": "https://www.aseanfootball.org/",
        "region": "ASIA_ASEAN",
        "layer": "REGIONAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "ASEAN",
        "status": "CANDIDATE",
        "notes": "Regional Southeast Asian football source; covers AFF competitions, member associations, fixtures, results and football information.",
    },
    {
        "source_id": "afc_asean",
        "name": "Asian Football Confederation Southeast Asia",
        "base_url": "https://www.the-afc.com/",
        "region": "ASIA_ASEAN",
        "layer": "REGIONAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "ASEAN",
        "status": "CANDIDATE",
        "notes": "AFC regional source for Southeast Asian competitions, fixtures, results and match information.",
    },
    {
        "source_id": "australia_football_official",
        "name": "Football Australia",
        "base_url": "https://www.footballaustralia.com.au/",
        "region": "ASIA_ASEAN",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "AUSTRALIA",
        "status": "CANDIDATE",
        "notes": "AFF member association and national football source.",
    },
    {
        "source_id": "brunei_nfabd_official",
        "name": "National Football Association of Brunei Darussalam",
        "base_url": "https://www.nfabd.org/",
        "region": "ASIA_ASEAN",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "BRUNEI",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "cambodia_ffc_official",
        "name": "Football Federation of Cambodia",
        "base_url": "https://www.the-fcc.com/",
        "region": "ASIA_ASEAN",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "CAMBODIA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "indonesia_pssi_official",
        "name": "Football Association of Indonesia",
        "base_url": "https://www.pssi.org/",
        "region": "ASIA_ASEAN",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "INDONESIA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "laos_lff_official",
        "name": "Lao Football Federation",
        "base_url": "https://laoff.org/",
        "region": "ASIA_ASEAN",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "LAOS",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "malaysia_fam_official",
        "name": "Football Association of Malaysia",
        "base_url": "https://www.fam.org.my/",
        "region": "ASIA_ASEAN",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "MALAYSIA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "myanmar_mff_official",
        "name": "Myanmar Football Federation",
        "base_url": "https://the-mff.org/",
        "region": "ASIA_ASEAN",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "MYANMAR",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "philippines_pff_official",
        "name": "Philippine Football Federation",
        "base_url": "https://pff.org.ph/",
        "region": "ASIA_ASEAN",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "PHILIPPINES",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "singapore_fas_official",
        "name": "Football Association of Singapore",
        "base_url": "https://www.fas.org.sg/",
        "region": "ASIA_ASEAN",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "SINGAPORE",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "timor_leste_fftl_official",
        "name": "Football Federation of Timor-Leste",
        "base_url": "https://fftl.tl/",
        "region": "ASIA_ASEAN",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "TIMOR_LESTE",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "thailand_fat_official",
        "name": "Football Association of Thailand",
        "base_url": "https://fathailand.org/",
        "region": "ASIA_ASEAN",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "THAILAND",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "vietnam_vff_official",
        "name": "Vietnam Football Federation",
        "base_url": "https://vff.org.vn/",
        "region": "ASIA_ASEAN",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "VIETNAM",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
]
