V13_ASIA_CENTRAL_SOURCE_CANDIDATES = [
    {
        "source_id": "cafa_official",
        "name": "Central Asian Football Association",
        "base_url": "https://the-cafa.com/",
        "region": "ASIA_CENTRAL",
        "layer": "REGIONAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "CENTRAL_ASIA",
        "status": "CANDIDATE",
        "notes": "Regional Central Asian football source covering CAFA competitions, member associations, fixtures, results and football information.",
    },
    {
        "source_id": "afc_central",
        "name": "Asian Football Confederation Central Zone",
        "base_url": "https://www.the-afc.com/",
        "region": "ASIA_CENTRAL",
        "layer": "REGIONAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "CENTRAL_ASIA",
        "status": "CANDIDATE",
        "notes": "AFC regional source for Central Asian competitions, fixtures, results and match information.",
    },
    {
        "source_id": "afghanistan_football_federation_official",
        "name": "Afghanistan Football Federation",
        "base_url": "https://aff.org.af/",
        "region": "ASIA_CENTRAL",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "AFGHANISTAN",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "iran_football_federation_official",
        "name": "Football Federation Islamic Republic of Iran",
        "base_url": "https://www.ffiri.ir/",
        "region": "ASIA_CENTRAL",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "IRAN",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "kyrgyz_football_union_official",
        "name": "Kyrgyz Football Union",
        "base_url": "https://kfu.kg/",
        "region": "ASIA_CENTRAL",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "KYRGYZSTAN",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "tajikistan_football_federation_official",
        "name": "Football Federation of Tajikistan",
        "base_url": "https://fft.tj/",
        "region": "ASIA_CENTRAL",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "TAJIKISTAN",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "turkmenistan_football_federation_official",
        "name": "Football Federation of Turkmenistan",
        "base_url": "https://tff.com.tm/",
        "region": "ASIA_CENTRAL",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "TURKMENISTAN",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "uzbekistan_football_association_official",
        "name": "Uzbekistan Football Association",
        "base_url": "https://ufa.uz/",
        "region": "ASIA_CENTRAL",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "UZBEKISTAN",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
]
