V13_EUROPE_COMPETITION_SOURCE_CANDIDATES = [
    {
        "source_id": "uefa_club_competitions",
        "name": "UEFA Club Competitions",
        "base_url": "https://www.uefa.com/",
        "region": "EUROPE",
        "layer": "COMPETITION",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "EUROPE_CLUB_COMPETITIONS",
        "status": "CANDIDATE",
        "notes": "European club competition source covering Champions League, Europa League and Conference League.",
    },
    {
        "source_id": "uefa_national_team_competitions",
        "name": "UEFA National Team Competitions",
        "base_url": "https://www.uefa.com/",
        "region": "EUROPE",
        "layer": "COMPETITION",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "EUROPE_NATIONAL_TEAM_COMPETITIONS",
        "status": "CANDIDATE",
        "notes": "European national-team competition source covering EURO, Nations League and UEFA youth competitions.",
    },
    {
        "source_id": "uefa_womens_competitions",
        "name": "UEFA Women's Competitions",
        "base_url": "https://www.uefa.com/womenseuro/",
        "region": "EUROPE",
        "layer": "COMPETITION",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "EUROPE_WOMENS_FOOTBALL",
        "status": "CANDIDATE",
        "notes": "European women's football competition source.",
    },
    {
        "source_id": "uefa_futsal_competitions",
        "name": "UEFA Futsal Competitions",
        "base_url": "https://www.uefa.com/futsal/",
        "region": "EUROPE",
        "layer": "COMPETITION",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "EUROPE_FUTSAL",
        "status": "CANDIDATE",
        "notes": "European futsal competition source.",
    },
]
