V13_ASIA_SOUTH_SOURCE_CANDIDATES = [
    {
        "source_id": "saff_official",
        "name": "South Asian Football Federation",
        "base_url": "https://saffederation.org/",
        "region": "ASIA_SOUTH",
        "layer": "REGIONAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "SOUTH_ASIA",
        "status": "CANDIDATE",
        "notes": "Regional South Asian football source; member associations: Bangladesh, Bhutan, India, Maldives, Nepal, Pakistan, Sri Lanka.",
    },
    {
        "source_id": "afc_south",
        "name": "Asian Football Confederation South Zone",
        "base_url": "https://www.the-afc.com/",
        "region": "ASIA_SOUTH",
        "layer": "REGIONAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "SOUTH_ASIA",
        "status": "CANDIDATE",
        "notes": "AFC regional source for South Asian competitions, fixtures, results and match information.",
    },
    {
        "source_id": "bangladesh_bff_official",
        "name": "Bangladesh Football Federation",
        "base_url": "https://www.bff.com.bd/",
        "region": "ASIA_SOUTH",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "BANGLADESH",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "bhutan_bff_official",
        "name": "Bhutan Football Federation",
        "base_url": "https://bhutanfootball.org/",
        "region": "ASIA_SOUTH",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "BHUTAN",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "india_aiff_official",
        "name": "All India Football Federation",
        "base_url": "https://www.the-aiff.com/",
        "region": "ASIA_SOUTH",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "INDIA",
        "status": "CANDIDATE",
        "notes": "National association source with public match-centre and competition information.",
    },
    {
        "source_id": "maldives_fam_official",
        "name": "Football Association of Maldives",
        "base_url": "https://famaldives.com/",
        "region": "ASIA_SOUTH",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "MALDIVES",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "nepal_anfa_official",
        "name": "All Nepal Football Association",
        "base_url": "https://www.the-anfa.com/",
        "region": "ASIA_SOUTH",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "NEPAL",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "pakistan_pff_official",
        "name": "Pakistan Football Federation",
        "base_url": "https://www.pff.com.pk/",
        "region": "ASIA_SOUTH",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "PAKISTAN",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
    {
        "source_id": "sri_lanka_ffsl_official",
        "name": "Football Federation of Sri Lanka",
        "base_url": "https://www.football.lk/",
        "region": "ASIA_SOUTH",
        "layer": "OFFICIAL",
        "access_type": "PUBLIC_WEB",
        "free": True,
        "coverage_scope": "SRI_LANKA",
        "status": "CANDIDATE",
        "notes": "National association source.",
    },
]
